workspace(name="hello-goku")

load("@bazel_tools//tools/build_defs/repo:git.bzl","git_repository")

git_repository(
    name = "com_github_gflags_gflags",
    commit = "986e8eed00ded8168ef4eaa6f925dc6be50b40fa",
    remote ="https://github.com/gflags/gflags",
)

git_repository(
    name = "glog",
    commit = "9f0b7d3bfe1542848f784e8d1c545b916cec6b3e",
    remote ="https://github.com/google/glog.git",
)


new_local_repository(
    name = "boost_libs",
    # pkg-config --variable=libdir x11
    path = "/home/ronghuang/work-local/boost/lib",
    build_file_content = """
cc_library(
    name = "boost",
    srcs = glob(["*.a"]),
    visibility = ["//visibility:public"],
)
""",
)


new_local_repository(
    name = "boost",
    path = "/home/ronghuang/work-local/boost/include",
    build_file_content = """
package(default_visibility = ["//visibility:public"])
cc_library(
    name = "headers",
    hdrs = glob(["**/*.h","**/*.hpp","**/*.ipp"])
)

"""
)